# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_stubs_for_B0minusv_cpp <- function(B0, G_stats) {
    .Call(`_ECoHeN_count_stubs_for_B0minusv_cpp`, B0, G_stats)
}

count_stubs_for_B0_cpp <- function(B0, G_stats) {
    .Call(`_ECoHeN_count_stubs_for_B0_cpp`, B0, G_stats)
}

lrd <- function(epoch, learning_rate, decay_rate) {
    .Call(`_ECoHeN_lrd`, epoch, learning_rate, decay_rate)
}

is_stable <- function(x, y, z) {
    .Call(`_ECoHeN_is_stable`, x, y, z)
}

is_cycle <- function(x, y, z) {
    .Call(`_ECoHeN_is_cycle`, x, y, z)
}

is_empty <- function(x) {
    .Call(`_ECoHeN_is_empty`, x)
}

main_search_decay_cpp <- function(alpha, B0, G_stats, learning_rate, decay_rate, max_iter, adj_method) {
    .Call(`_ECoHeN_main_search_decay_cpp`, alpha, B0, G_stats, learning_rate, decay_rate, max_iter, adj_method)
}

smallest_indices1 <- function(x, N) {
    .Call(`_ECoHeN_smallest_indices1`, x, N)
}

smallest_indices2 <- function(x, N) {
    .Call(`_ECoHeN_smallest_indices2`, x, N)
}

smallest_indices3 <- function(x, N) {
    .Call(`_ECoHeN_smallest_indices3`, x, N)
}

smallest_indices4 <- function(x, N) {
    .Call(`_ECoHeN_smallest_indices4`, x, N)
}

index_Cpp2R <- function(x) {
    .Call(`_ECoHeN_index_Cpp2R`, x)
}

index_R2Cpp <- function(x) {
    .Call(`_ECoHeN_index_R2Cpp`, x)
}

c_integer <- function(x, y) {
    .Call(`_ECoHeN_c_integer`, x, y)
}

vector_equals_string <- function(x, s) {
    .Call(`_ECoHeN_vector_equals_string`, x, s)
}

which_true <- function(x) {
    .Call(`_ECoHeN_which_true`, x)
}

subset_matrix <- function(M, rows, cols) {
    .Call(`_ECoHeN_subset_matrix`, M, rows, cols)
}

